### PR TITLE
Corrected all grammatical errors I could find.

### PR DESCRIPTION
**Pull request by D-Maxwell**

### CODE REVIEW

**Review by peotr26 — CHANGES_REQUESTED** [review]
Je ne vais prendre que les fautes d'orthographes. Un saut de ligne et un nouveau paragraphe ne sont pas la même chose.

**Review by peotr26 — CHANGES_REQUESTED** [review]
Maxim, Dieu est le nom d'une divinité donc je ne peux pas accepter ce commit, de plus je ne souhaite pas raccourcir _100 000_ par _100k_, on est dans un texte rédigé.

**Comment by D-Maxwell** [comment]
> Je ne vais prendre que les fautes d'orthographes. Un saut de ligne et un nouveau paragraphe ne sont pas la même chose.

Here, declaring a new paragraph would have made more sense ; or rather, this is the way I was expecting it to be arranged.
Use `<br>` if you wish I guess. It's old HTML, but alright.


> Maxim, Dieu est le nom d'une divinité donc je ne peux pas accepter ce commit, de plus je ne souhaite pas raccourcir _100 000_ par _100k_, on est dans un texte rédigé.

"God" is indeed the name of the christian divinity, however, —as that is too generic of a name— as to account for secularism and readers which do not share the faith of Terry Davis, I have limited its use, although it is still present within the document.
It occurred to me you would be against this change, the intent of which was to avoid repetition ; but it would seem you have interpreted this as some sort of censorship against christianity. You are over-reacting, and I advise you to accept this change, at least partially ; **as the amount of times the term "God" was explicitly used makes it not only quite redundant, but takes away its value and importance.**

As for "100k"... that is precisely the point. As this is a proper article, please avoid values higher than 10^3. *SI* conventions exist, and are much more formal than explicit values written in such a way that they feel and look childish.
It is not about "shortening" values, but rather about consistency and formalness.
Unless your intent was to somehow "impress" the reader by a "big number" ? I choose to believe that was in fact not the case, but I care to let you know this is the idea your writing leads one towards.

-----

### TL ; DR
`{/}` grammar errors
`{-}` `<p>` in place of `<br>`
`{/}` avoiding redundancy
`{/}` use of *SI* factors

##### (`/` : unchanged, `-` : reversion, `+` : changed)

**Review by peotr26 — APPROVED** [review]

**Review by peotr26 — APPROVED** [review]

**Comment by peotr26** [comment]
I'm going to accept your pull request, but I'm also going to revert some of your changes.

**Pull request merged**
